-- MySQL Script generated by MySQL Workbench
-- Tue Jul 20 11:15:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbturma28
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbturma28
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbturma28` DEFAULT CHARACTER SET utf8 ;
USE `dbturma28` ;

-- -----------------------------------------------------
-- Table `dbturma28`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbturma28`.`Funcionario` (
  `id funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`id funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbturma28`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbturma28`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT(2) NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbturma28`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbturma28`.`venda` (
  `idvenda` INT NOT NULL,
  `data` DATE NOT NULL,
  `fk_funcionario` INT NOT NULL,
  `fk_produto` INT NOT NULL,
  PRIMARY KEY (`idvenda`, `fk_produto`),
  INDEX `fk_venda_Funcionario_idx` (`fk_funcionario` ASC) VISIBLE,
  INDEX `fk_venda_Produto1_idx` (`fk_produto` ASC) VISIBLE,
  CONSTRAINT `fk_venda_Funcionario`
    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `dbturma28`.`Funcionario` (`id funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_Produto1`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `dbturma28`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
