-- MySQL Script generated by MySQL Workbench
-- Tue Jul 20 15:23:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Turma28
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Turma28
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Turma28` DEFAULT CHARACTER SET utf8 ;
USE `Turma28` ;

-- -----------------------------------------------------
-- Table `Turma28`.`Rh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Turma28`.`Rh` (
  `id_Rh` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `salario` DECIMAL(60) NOT NULL,
  `data de nascimento` DATE NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Rh`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
